server:
  port: 8085

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/NewbieZilani/ConfigServer_Microservice
          clone-on-start: true
